name: LPC-MiniMessage
version: "${version}"
main: de.ayont.lpc.bukkit.LPCPlugin
api-version: "1.21"
authors: [TurboJax, Ayont]
depend: [LuckPerms]
softdepend: [PlaceholderAPI]
description: Continuation of LPC-Minimessage by Ayont
website: https://modrinth.com/plugin/lpc-chat
commands:
  lpc:
    description: Reload the configuration.
    permission: lpc.reload
    usage: "Usage: /lpc reload"
